function [snapshot_times, position, velocity, observable] = classicalLeapfrog(obj, x_0, v_0, tdep, v_cutoff, cap_frame_every, max_frames)
%CLASSICALLEAPFROG Run classical Hamiltonian dynamics of a unit mass point
%particle in a potential field.


    % How far into the past to look to determine if the evolution has
    % converged
    min_frames = 100;


    % Dim+1 = 2+1 = 3
%     dt = 0.9 * obj.step_size^3;
    dt = 1e-4;
    
    fn_oracle = @obj.eval_fn;
    grad_fn = @obj.eval_grad;
    bounds = obj.normalized_bounds;
    tdep_fn = @tdep.eval_tdep;

    [snapshot_times, position, velocity, observable] = convergenceHamiltonianLeapfrog(...
        x_0, ...
        v_0, ...
        fn_oracle, ...
        grad_fn, ...
        bounds, ...
        dt, ...
        tdep_fn, ...
        min_frames, ...
        max_frames, ...
        v_cutoff, ...
        cap_frame_every);
end
